version: '3.9'

services:
  cassandra:
    image: cassandra:latest
    ports:
      - 9042:9042
    volumes:
      - ./Data:/var/lib/cassandra
      - ./doc:/opt/cassandra/doc
      - ./config/cassandra.yaml:/etc/cassandra/cassandra.yaml
    environment:
      - CASSANDRA_CLUSTER_NAME=cloudinfra
